# Generated by Django 6.0.4 on 2026-06-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_alter_course_course_code"),
        ("enrollments", "0001_initial"),
        ("students", "0002_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"ordering": ["student", "course"]},
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="students.student"
            ),
        ),
    ]
