# Generated by Django 6.0.4 on 2026-06-05 10:05

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["registration_number"]},
        ),
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[students.models.validate_registration_number],
            ),
        ),
    ]
