# Generated by Django 6.0.4 on 2026-06-05 12:08

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[students.models.validate_registration_number],
            ),
        ),
    ]
