# Generated by Django 6.0.4 on 2026-06-05 12:49

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_registration_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(
                help_text="Example: AIMS20260001 (AIMS + Cohort Year + Student Number)",
                max_length=12,
                unique=True,
                validators=[students.models.validate_registration_number],
            ),
        ),
    ]
