# Generated by Django 6.0.4 on 2026-06-05 10:05

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["course_code"]},
        ),
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[courses.models.validate_course_code],
            ),
        ),
    ]
