# Generated by Django 6.0.4 on 2026-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_alter_course_course_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="capacity",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Maximum number of students allowed in this course.",
            ),
        ),
    ]
