# Generated by Django 6.0.4 on 2026-06-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_capacity"),
        ("programs", "0002_alter_program_program_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="program",
        ),
        migrations.AddField(
            model_name="course",
            name="programs",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="programs.program"
            ),
        ),
    ]
