# Generated by Django 6.0.4 on 2026-06-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="program_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="program",
            unique_together={("program_name", "specialization")},
        ),
    ]
